name: hydrated_riverpod
description: An extension to the riverpod state management library which automatically persists and restores riverpod states.
version: 0.0.3
# publish_to: https://pub.dartlang.org
repository: https://github.com/hydrz/hydrated_riverpod
issue_tracker: https://github.com/hydrz/hydrated_riverpod
homepage: https://github.com/hydrz/hydrated_riverpod
documentation: https://github.com/hydrz/hydrated_riverpod

environment:
  sdk: ">=2.17.6 <3.0.5"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  json_serializable: ^6.5.4
  meta: ^1.8.0
  riverpod: ^2.0.2
  synchronized: ^3.0.0+3

dev_dependencies:
  crypto: ^3.0.1
  mocktail: ^0.3.0
  path: ^1.8.0
  test: ^1.19.5
  uuid: ^3.0.6
  very_good_analysis: ^2.4.0
